export const siteConfig = {
  name: "Orbyza",
  tagline: "Elite Digital Marketing Agency Jaipur & Delhi | Performance SEO & SEM",
  description:
    "Orbyza is the top-rated digital marketing agency in Jaipur and Delhi, specializing in 420% ROI performance marketing. We provide elite SEO services, surgical Google Ads (SEM), and high-conversion web design for brands in India, USA, Canada, and Europe. Best digital marketing company in Jaipur and Delhi for scaling enterprises.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://orbyza.com",
  email: "growth@orbyza.com",
  phone: "+91-XXXXXXXXXX", 
  address: "Mansarovar, Jaipur, Rajasthan, India",
  author: "harshit",
  social: {
    twitter: "https://twitter.com/orbyza",
    linkedin: "https://linkedin.com/company/orbyza",
    instagram: "https://instagram.com/orbyza",
    facebook: "https://facebook.com/orbyza",
    youtube: "https://youtube.com/@orbyza",
    freelancer: "https://www.freelancer.com/u/mintw2",
  },
  geo: {
    region: "IN-RJ",
    placename: "Jaipur",
    latitude: "26.9124",
    longitude: "75.7873",
    position: "26.9124;75.7873",
    icbm: "26.9124, 75.7873",
  },
  ogImage: "/og-image.jpg",
  keywords: [
    "digital marketing agency in jaipur",
    "marketing agency in jaipur",
    "jaipur digital marketing",
    "digital marketing company in jaipur",
    "digital marketing agency jaipur",
    "best digital marketing agency in jaipur",
    "digital marketing in delhi",
    "digital marketing in bangalore",
    "digital marketing agency bangalore",
    "digital marketing company in delhi",
    "digital marketing agency in delhi",
    "best digital marketing agency in delhi",
    "digital marketing company in mansarovar jaipur",
    "social media marketing agency in jaipur",
    "performance marketing agency in jaipur",
    "top digital marketing agency in jaipur",
    "seo company in jaipur",
    "digital marketing usa",
    "digital marketing canada",
    "digital marketing europe",
    "best digital marketing company in india",
  ],
  founded: "2020",
  teamSize: "25+",
  clientsServed: "150+",
  projectsCompleted: "500+",
  yearsExperience: "5+",
};
